import './ReportSection.css';

export default function ReportSection() {
  return (
    <section className="section amber" data-screen-label="AI Report">
      <div className="shell">
        <div className="report-grid">
          <div className="report-copy">
            <div className="section-label" style={{ color: 'var(--ap-amber-deep)' }}>AI report sample</div>
            <h2 className="section-title">
              A PDF for the bank. <br /><em>Generated by chat.</em>
            </h2>
            <p className="section-sub" style={{ marginTop: 20 }}>
              Microfinance officers, accountants, and tax filings all want the same thing:
              a clean monthly statement. APSIMS turns your chat history into a real document —
              delivered as a WhatsApp attachment, ready to forward.
            </p>
            <ul className="report-features">
              {[
                ['Weekly + monthly summaries', 'ti-calendar'],
                ['Top sellers, low stock, credit overdue', 'ti-chart-arrows-vertical'],
                ['Forwardable PDF — bank-ready', 'ti-file-text'],
                ['Plain language, not accounting jargon', 'ti-message-circle'],
              ].map(([t, ic], i) => (
                <li key={i}>
                  <span className="rf-icon"><i className={`ti ${ic}`} /></span>
                  {t}
                </li>
              ))}
            </ul>
          </div>

          <div className="report-paper">
            <div className="report-head">
              <div>
                <div className="biz">Mama Ade Provisions</div>
                <div className="period">Weekly Report · May 19–25, 2026</div>
              </div>
              <div className="rh-right">APSIMS<br />v1.0</div>
            </div>
            <div className="report-body">
              <div className="report-kpis">
                {[
                  { label: 'Revenue', val: '₦184,200', delta: '↑ 12.4%', bad: false },
                  { label: 'Profit',  val: '₦43,200',  delta: '↑ 8.1%',  bad: false },
                  { label: 'Margin',  val: '23.4%',    delta: '↓ -1.2pp', bad: true },
                ].map((k, i) => (
                  <div className="kpi" key={i}>
                    <div className="kpi-label">{k.label}</div>
                    <div className="kpi-val">{k.val}</div>
                    <div className={`kpi-delta ${k.bad ? 'warn' : ''}`}>{k.delta}</div>
                  </div>
                ))}
              </div>

              <div className="report-section">
                <h4>Top Sellers</h4>
                <div className="report-rows">
                  {[
                    ['Rice 50kg', '42 bags · ₦1,600/bag', '₦67,200'],
                    ['Indomie carton', '31 ctns · ₦1,900/ctn', '₦58,900'],
                    ['Palm oil 5L', '14 btls · ₦4,200/btl', '₦41,400'],
                  ].map(([n, q, a], i) => (
                    <div className="report-row" key={i}>
                      <div className="pname">{n}</div>
                      <div className="pqty">{q}</div>
                      <div className="pamt">{a}</div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="report-summary">
                <div className="rs-label">AI Summary</div>
                Strong week for rice and Indomie. Palm oil stock dropped below threshold —
                consider restocking before the weekend. Credit owed to you is up ₦4,200; two
                customers overdue.
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
